import json
import pathlib

base = pathlib.Path("app/translations")

translations = {
    "ar": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "المستأجرون", "ORDERS": "الطلبات", "LOG_OUT": "تسجيل الخروج"},
        "COMMON": {"ACTIVE": "نشط", "INACTIVE": "غير نشط", "CONFIGURED": "مُهيَّأ", "MISSING": "مفقود", "SAVE_CHANGES": "حفظ التغييرات", "CREATE": "إنشاء", "EDIT": "تعديل", "APPLY": "تطبيق", "CLEAR": "مسح", "VALIDATE": "التحقق", "SHOW": "إظهار", "HIDE": "إخفاء", "COPY": "نسخ", "COPIED": "تم النسخ.", "PREVIOUS": "السابق", "NEXT": "التالي", "OPEN": "فتح", "SEARCH": "بحث", "ALL_TENANTS": "جميع المستأجرين", "ALL_STATUSES": "جميع الحالات", "ALL_STATES": "جميع الحالات", "ALL_CONFIGURATIONS": "جميع الإعدادات", "SHOWING": "عرض", "OF": "من", "PAGE": "صفحة", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "مدير", "SUPPORT": "دعم", "USER": "مستخدم"},
        "DASHBOARD": {"TITLE": "Integration Dashboard", "SUBTITLE": "عرض تشغيلي لمدفوعات Ticket Tailor غير المتصلة وطلبات الدفع من Nicky.", "CUSTOMER_CONNECTIONS": "اتصالات العملاء", "RECENT_WEBHOOKS": "WebHooks الأخيرة", "RECENT_ORDERS": "الطلبات الأخيرة", "METRIC_TENANTS": "المستأجرون", "METRIC_TOTAL_ORDERS": "إجمالي الطلبات", "METRIC_TOTAL_WEBHOOKS": "إجمالي WebHooks", "METRIC_ACTIVE": "{{count}} نشط", "METRIC_ALL_TIME": "منذ البداية"},
        "TENANTS": {"TITLE": "اتصالات العملاء", "SUBTITLE": "إدارة اتصال Ticket Tailor وحساب الدفع في Nicky وإعداد WebHook لكل عميل.", "BUTTON_NEW": "Tenant جديد", "NO_TENANTS": "لم يتم تهيئة أي Tenant بعد", "NO_TENANTS_HINT": "أنشئ Tenant لربط حساب Ticket Tailor بـ Nicky.", "TABLE_NICKY_EMAIL": "بريد Nicky الإلكتروني", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "الأصل", "TABLE_CREATED": "تاريخ الإنشاء", "TABLE_UPDATED": "تاريخ التحديث", "FILTER_ACTIVE": "نشط", "FILTER_CONFIG": "الإعداد", "FILTER_CONFIGURED": "مُهيَّأ", "FILTER_MISSING": "إعداد مفقود", "FILTER_PLACEHOLDER": "Tenant أو الاسم", "FILTER_ACTIVE_OPTION": "نشط", "FILTER_INACTIVE_OPTION": "غير نشط", "FORM_TITLE_NEW": "Tenant جديد", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "الاسم", "FORM_LABEL_UUID": "UUID الخاص بـ Tenant", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "بريد Nicky الإلكتروني", "FORM_LABEL_ASSET": "الأصل", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "الصق API key الخاصة بـ Nicky", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "اتركه فارغاً للإبقاء على المفتاح الحالي", "FORM_PLACEHOLDER_TT_KEY_NEW": "الصق API key الخاصة بـ Ticket Tailor", "FORM_PLACEHOLDER_TT_KEY_EDIT": "اتركه فارغاً للإبقاء على المفتاح الحالي", "FORM_PLACEHOLDER_ASSET": "تحقق أولاً من API key الخاصة بـ Nicky", "FORM_BUTTON_CREATE": "إنشاء Tenant", "FORM_BUTTON_SAVE": "حفظ التغييرات", "FORM_BUTTON_BACK": "العودة إلى Tenants", "FORM_BUTTON_DEACTIVATE": "تعطيل Tenant", "FORM_WEBHOOK_TITLE": "WebHook الخاص بـ Ticket Tailor", "FORM_WEBHOOK_HINT": "انسخ رابط WebHook هذا للخدمة المصغرة وهيئه في Ticket Tailor ضمن الإعدادات > API > WebHook.", "NOTICE_SAVED": "تم حفظ Tenant.", "NOTICE_WEBHOOK_FAILED": "تم حفظ Tenant، لكن تسجيل WebHook في Nicky فشل — يرجى المحاولة مرة أخرى لاحقاً.", "VALIDATION_VALIDATING": "جارٍ التحقق...", "VALIDATION_NICKY_OK": "تم التحقق من API key الخاصة بـ Nicky.", "VALIDATION_TT_OK": "تم التحقق من API key الخاصة بـ Ticket Tailor.", "VALIDATION_ERROR_NICKY_EMPTY": "الصق API key الخاصة بـ Nicky أولاً.", "VALIDATION_ERROR_TT_EMPTY": "الصق API key الخاصة بـ Ticket Tailor أولاً.", "VALIDATION_FAILED": "فشل التحقق"},
        "ORDERS": {"TITLE": "الطلبات", "SUBTITLE": "طلبات Ticket Tailor المرتبطة بطلبات الدفع في Nicky.", "NO_ORDERS": "لم يتم التقاط أي طلبات بعد", "NO_ORDERS_HINT": "تظهر الطلبات هنا عندما يرسل Ticket Tailor WebHook لدفع Nicky غير المتصل.", "TABLE_ORDER": "الطلب", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "المشتري", "TABLE_AMOUNT": "المبلغ", "TABLE_NICKY_PR": "PR في Nicky", "TABLE_NICKY_STATUS": "حالة Nicky", "TABLE_TT_STATE": "حالة Ticket Tailor", "TABLE_UPDATED": "تاريخ التحديث", "FILTER_UPDATED_FROM": "محدَّث من", "FILTER_UPDATED_TO": "محدَّث حتى", "FILTER_ALL_STATES": "جميع الحالات", "FILTER_PENDING": "طلب معلق", "FILTER_CONFIRMED": "تم تأكيد الدفع", "FILTER_VOIDED": "تذاكر ملغاة", "DETAIL_BUTTON_BACK": "العودة إلى الطلبات", "DETAIL_SECTION_MAPPING": "ربط الطلب", "DETAIL_SECTION_ACTIONS": "الإجراءات", "DETAIL_SECTION_LOGS": "سجلات الطلب", "DETAIL_SECTION_PAYLOAD": "Payload الخام من Ticket Tailor", "DETAIL_ACTION_CREATE_PR": "إنشاء طلب دفع Nicky", "DETAIL_ACTION_CONFIRM_TT": "تأكيد الدفع في Ticket Tailor", "DETAIL_MAPPING_TT_ORDER": "طلب Ticket Tailor", "DETAIL_MAPPING_NICKY_PR": "طلب دفع Nicky", "DETAIL_MAPPING_NICKY_BILL": "المعرف المختصر لفاتورة Nicky", "DETAIL_MAPPING_NICKY_RECEIVER": "المستلم في Nicky", "DETAIL_MAPPING_NICKY_URL": "رابط الدفع في Nicky", "DETAIL_MAPPING_NICKY_STATUS": "حالة Nicky", "DETAIL_MAPPING_TT_CONFIRMED": "تم تأكيد دفع Ticket Tailor في", "DETAIL_MAPPING_TT_VOIDED": "تم إلغاء التذاكر الصادرة في", "DETAIL_MAPPING_VOID_REASON": "سبب إلغاء التذكرة", "STATE_CONFIRMED": "تم تأكيد الدفع", "STATE_VOIDED": "تذاكر ملغاة", "STATE_PENDING": "طلب معلق"},
        "WEBHOOKS": {"TABLE_RECEIVED": "تاريخ الاستلام", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "المصدر", "TABLE_TYPE": "النوع", "TABLE_STATUS": "الحالة", "NO_WEBHOOKS": "لم يتم استلام أي WebHook بعد", "NO_WEBHOOKS_HINT": "ستظهر WebHooks من Ticket Tailor وNicky هنا.", "FILTER_RECEIVED_FROM": "مستلَم من", "FILTER_RECEIVED_TO": "مستلَم حتى", "FILTER_ALL": "جميع الحالات", "FILTER_PROCESSED": "تمت معالجته", "FILTER_FAILED": "فشل", "FILTER_IGNORED": "تم تجاهله", "FILTER_RECEIVED": "مستلَم"},
        "LOGS": {"TABLE_CREATED": "تاريخ الإنشاء", "TABLE_EVENT": "الحدث", "TABLE_MESSAGE": "الرسالة", "NO_LOGS": "لا توجد سجلات لهذا الطلب."},
        "LANG": {"LABEL": "اللغة"},
    },
    "da": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "Lejere", "ORDERS": "Ordrer", "LOG_OUT": "Log ud"},
        "COMMON": {"ACTIVE": "Aktiv", "INACTIVE": "Inaktiv", "CONFIGURED": "Konfigureret", "MISSING": "Mangler", "SAVE_CHANGES": "Gem ændringer", "CREATE": "Opret", "EDIT": "Rediger", "APPLY": "Anvend", "CLEAR": "Ryd", "VALIDATE": "Valider", "SHOW": "Vis", "HIDE": "Skjul", "COPY": "Kopiér", "COPIED": "Kopieret.", "PREVIOUS": "Forrige", "NEXT": "Næste", "OPEN": "Åbn", "SEARCH": "Søg", "ALL_TENANTS": "Alle lejere", "ALL_STATUSES": "Alle statusser", "ALL_STATES": "Alle tilstande", "ALL_CONFIGURATIONS": "Alle konfigurationer", "SHOWING": "Viser", "OF": "af", "PAGE": "Side", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "Administrator", "SUPPORT": "Support", "USER": "Bruger"},
        "DASHBOARD": {"TITLE": "Integrations-Dashboard", "SUBTITLE": "Driftsvisning af Ticket Tailor offline-betalinger og Nicky betalingsanmodninger.", "CUSTOMER_CONNECTIONS": "Kundeforbindelser", "RECENT_WEBHOOKS": "Seneste WebHooks", "RECENT_ORDERS": "Seneste ordrer", "METRIC_TENANTS": "Lejere", "METRIC_TOTAL_ORDERS": "Ordrer i alt", "METRIC_TOTAL_WEBHOOKS": "WebHooks i alt", "METRIC_ACTIVE": "{{count}} aktive", "METRIC_ALL_TIME": "til alle tider"},
        "TENANTS": {"TITLE": "Kundeforbindelser", "SUBTITLE": "Administrer hver kundes Ticket Tailor-forbindelse, Nicky betalingskonto og WebHook-opsætning.", "BUTTON_NEW": "Ny Tenant", "NO_TENANTS": "Ingen Tenants konfigureret endnu", "NO_TENANTS_HINT": "Opret en Tenant for at forbinde en Ticket Tailor-konto med Nicky.", "TABLE_NICKY_EMAIL": "Nicky e-mail", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "Aktiv", "TABLE_CREATED": "Oprettet", "TABLE_UPDATED": "Opdateret", "FILTER_ACTIVE": "Aktiv", "FILTER_CONFIG": "Konfiguration", "FILTER_CONFIGURED": "Konfigureret", "FILTER_MISSING": "Manglende konfiguration", "FILTER_PLACEHOLDER": "Tenant eller navn", "FILTER_ACTIVE_OPTION": "Aktiv", "FILTER_INACTIVE_OPTION": "Inaktiv", "FORM_TITLE_NEW": "Ny Tenant", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "Navn", "FORM_LABEL_UUID": "Tenant UUID", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "Nicky e-mail", "FORM_LABEL_ASSET": "Aktiv", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "Indsæt Nicky API key", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "Lad feltet stå tomt for at beholde den eksisterende", "FORM_PLACEHOLDER_TT_KEY_NEW": "Indsæt Ticket Tailor API key", "FORM_PLACEHOLDER_TT_KEY_EDIT": "Lad feltet stå tomt for at beholde den eksisterende", "FORM_PLACEHOLDER_ASSET": "Valider Nicky API key først", "FORM_BUTTON_CREATE": "Opret Tenant", "FORM_BUTTON_SAVE": "Gem ændringer", "FORM_BUTTON_BACK": "Tilbage til Tenants", "FORM_BUTTON_DEACTIVATE": "Deaktiver Tenant", "FORM_WEBHOOK_TITLE": "Ticket Tailor WebHook", "FORM_WEBHOOK_HINT": "Kopiér denne mikrotjeneste WebHook-URL og konfigurér den i Ticket Tailor under Indstillinger > API > WebHook.", "NOTICE_SAVED": "Tenant gemt.", "NOTICE_WEBHOOK_FAILED": "Tenant gemt, men Nicky WebHook-registrering mislykkedes — prøv venligst igen senere.", "VALIDATION_VALIDATING": "Validerer...", "VALIDATION_NICKY_OK": "Nicky API key valideret.", "VALIDATION_TT_OK": "Ticket Tailor API key valideret.", "VALIDATION_ERROR_NICKY_EMPTY": "Indsæt en Nicky API key først.", "VALIDATION_ERROR_TT_EMPTY": "Indsæt en Ticket Tailor API key først.", "VALIDATION_FAILED": "Validering mislykkedes"},
        "ORDERS": {"TITLE": "Ordrer", "SUBTITLE": "Ticket Tailor ordrer knyttet til Nicky betalingsanmodninger.", "NO_ORDERS": "Ingen ordrer registreret endnu", "NO_ORDERS_HINT": "Ordrer vises her, når Ticket Tailor sender en WebHook for en Nicky offline-betaling.", "TABLE_ORDER": "Ordre", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "Køber", "TABLE_AMOUNT": "Beløb", "TABLE_NICKY_PR": "Nicky PR", "TABLE_NICKY_STATUS": "Nicky status", "TABLE_TT_STATE": "Ticket Tailor tilstand", "TABLE_UPDATED": "Opdateret", "FILTER_UPDATED_FROM": "Opdateret fra", "FILTER_UPDATED_TO": "Opdateret til", "FILTER_ALL_STATES": "Alle tilstande", "FILTER_PENDING": "Ordre afventer", "FILTER_CONFIRMED": "Betaling bekræftet", "FILTER_VOIDED": "Billetter annulleret", "DETAIL_BUTTON_BACK": "Tilbage til ordrer", "DETAIL_SECTION_MAPPING": "Ordretilknytning", "DETAIL_SECTION_ACTIONS": "Handlinger", "DETAIL_SECTION_LOGS": "Ordrelogge", "DETAIL_SECTION_PAYLOAD": "Råt Ticket Tailor Payload", "DETAIL_ACTION_CREATE_PR": "Opret Nicky betalingsanmodning", "DETAIL_ACTION_CONFIRM_TT": "Bekræft Ticket Tailor betaling", "DETAIL_MAPPING_TT_ORDER": "Ticket Tailor ordre", "DETAIL_MAPPING_NICKY_PR": "Nicky betalingsanmodning", "DETAIL_MAPPING_NICKY_BILL": "Nicky faktura kort-id", "DETAIL_MAPPING_NICKY_RECEIVER": "Nicky modtager", "DETAIL_MAPPING_NICKY_URL": "Nicky betalings-URL", "DETAIL_MAPPING_NICKY_STATUS": "Nicky status", "DETAIL_MAPPING_TT_CONFIRMED": "Ticket Tailor betaling bekræftet den", "DETAIL_MAPPING_TT_VOIDED": "Udstedte billetter annulleret den", "DETAIL_MAPPING_VOID_REASON": "Årsag til billetannullering", "STATE_CONFIRMED": "Betaling bekræftet", "STATE_VOIDED": "Billetter annulleret", "STATE_PENDING": "Ordre afventer"},
        "WEBHOOKS": {"TABLE_RECEIVED": "Modtaget", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "Kilde", "TABLE_TYPE": "Type", "TABLE_STATUS": "Status", "NO_WEBHOOKS": "Ingen WebHooks modtaget endnu", "NO_WEBHOOKS_HINT": "WebHooks fra Ticket Tailor og Nicky vises her.", "FILTER_RECEIVED_FROM": "Modtaget fra", "FILTER_RECEIVED_TO": "Modtaget til", "FILTER_ALL": "Alle statusser", "FILTER_PROCESSED": "Behandlet", "FILTER_FAILED": "Mislykkedes", "FILTER_IGNORED": "Ignoreret", "FILTER_RECEIVED": "Modtaget"},
        "LOGS": {"TABLE_CREATED": "Oprettet", "TABLE_EVENT": "Hændelse", "TABLE_MESSAGE": "Besked", "NO_LOGS": "Ingen logge for denne ordre."},
        "LANG": {"LABEL": "Sprog"},
    },
    "he": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "דיירים", "ORDERS": "הזמנות", "LOG_OUT": "התנתק"},
        "COMMON": {"ACTIVE": "פעיל", "INACTIVE": "לא פעיל", "CONFIGURED": "מוגדר", "MISSING": "חסר", "SAVE_CHANGES": "שמור שינויים", "CREATE": "צור", "EDIT": "ערוך", "APPLY": "החל", "CLEAR": "נקה", "VALIDATE": "אמת", "SHOW": "הצג", "HIDE": "הסתר", "COPY": "העתק", "COPIED": "הועתק.", "PREVIOUS": "הקודם", "NEXT": "הבא", "OPEN": "פתח", "SEARCH": "חפש", "ALL_TENANTS": "כל הדיירים", "ALL_STATUSES": "כל הסטטוסים", "ALL_STATES": "כל המצבים", "ALL_CONFIGURATIONS": "כל ההגדרות", "SHOWING": "מציג", "OF": "מתוך", "PAGE": "עמוד", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "מנהל", "SUPPORT": "תמיכה", "USER": "משתמש"},
        "DASHBOARD": {"TITLE": "Integration Dashboard", "SUBTITLE": "תצוגה תפעולית של תשלומים לא מקוונים של Ticket Tailor ובקשות תשלום של Nicky.", "CUSTOMER_CONNECTIONS": "חיבורי לקוחות", "RECENT_WEBHOOKS": "WebHooks אחרונים", "RECENT_ORDERS": "הזמנות אחרונות", "METRIC_TENANTS": "דיירים", "METRIC_TOTAL_ORDERS": "סך הזמנות", "METRIC_TOTAL_WEBHOOKS": "סך WebHooks", "METRIC_ACTIVE": "{{count}} פעילים", "METRIC_ALL_TIME": "כל הזמנים"},
        "TENANTS": {"TITLE": "חיבורי לקוחות", "SUBTITLE": "נהל את חיבור Ticket Tailor, חשבון התשלום של Nicky והגדרת WebHook של כל לקוח.", "BUTTON_NEW": "Tenant חדש", "NO_TENANTS": "לא הוגדרו Tenants עדיין", "NO_TENANTS_HINT": "צור Tenant כדי לחבר חשבון Ticket Tailor עם Nicky.", "TABLE_NICKY_EMAIL": 'דוא"ל Nicky', "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "נכס", "TABLE_CREATED": "נוצר", "TABLE_UPDATED": "עודכן", "FILTER_ACTIVE": "פעיל", "FILTER_CONFIG": "הגדרה", "FILTER_CONFIGURED": "מוגדר", "FILTER_MISSING": "הגדרה חסרה", "FILTER_PLACEHOLDER": "Tenant או שם", "FILTER_ACTIVE_OPTION": "פעיל", "FILTER_INACTIVE_OPTION": "לא פעיל", "FORM_TITLE_NEW": "Tenant חדש", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "שם", "FORM_LABEL_UUID": "UUID של Tenant", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": 'דוא"ל Nicky', "FORM_LABEL_ASSET": "נכס", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "הדבק API key של Nicky", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "השאר ריק כדי לשמור את הקיים", "FORM_PLACEHOLDER_TT_KEY_NEW": "הדבק API key של Ticket Tailor", "FORM_PLACEHOLDER_TT_KEY_EDIT": "השאר ריק כדי לשמור את הקיים", "FORM_PLACEHOLDER_ASSET": "אמת תחילה את API key של Nicky", "FORM_BUTTON_CREATE": "צור Tenant", "FORM_BUTTON_SAVE": "שמור שינויים", "FORM_BUTTON_BACK": "חזור ל-Tenants", "FORM_BUTTON_DEACTIVATE": "השבת Tenant", "FORM_WEBHOOK_TITLE": "WebHook של Ticket Tailor", "FORM_WEBHOOK_HINT": "העתק את כתובת ה-WebHook של המיקרו-שירות והגדר אותה ב-Ticket Tailor תחת הגדרות > API > WebHook.", "NOTICE_SAVED": "Tenant נשמר.", "NOTICE_WEBHOOK_FAILED": "Tenant נשמר, אך רישום WebHook של Nicky נכשל — נסה שוב מאוחר יותר.", "VALIDATION_VALIDATING": "מאמת...", "VALIDATION_NICKY_OK": "API key של Nicky אומתה.", "VALIDATION_TT_OK": "API key של Ticket Tailor אומתה.", "VALIDATION_ERROR_NICKY_EMPTY": "הדבק תחילה API key של Nicky.", "VALIDATION_ERROR_TT_EMPTY": "הדבק תחילה API key של Ticket Tailor.", "VALIDATION_FAILED": "האימות נכשל"},
        "ORDERS": {"TITLE": "הזמנות", "SUBTITLE": "הזמנות Ticket Tailor המשויכות לבקשות תשלום של Nicky.", "NO_ORDERS": "לא נלכדו הזמנות עדיין", "NO_ORDERS_HINT": "הזמנות יופיעו כאן כאשר Ticket Tailor ישלח WebHook עבור תשלום לא מקוון של Nicky.", "TABLE_ORDER": "הזמנה", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "קונה", "TABLE_AMOUNT": "סכום", "TABLE_NICKY_PR": "PR של Nicky", "TABLE_NICKY_STATUS": "סטטוס Nicky", "TABLE_TT_STATE": "מצב Ticket Tailor", "TABLE_UPDATED": "עודכן", "FILTER_UPDATED_FROM": "עודכן מ", "FILTER_UPDATED_TO": "עודכן עד", "FILTER_ALL_STATES": "כל המצבים", "FILTER_PENDING": "הזמנה ממתינה", "FILTER_CONFIRMED": "תשלום אושר", "FILTER_VOIDED": "כרטיסים בוטלו", "DETAIL_BUTTON_BACK": "חזור להזמנות", "DETAIL_SECTION_MAPPING": "מיפוי הזמנה", "DETAIL_SECTION_ACTIONS": "פעולות", "DETAIL_SECTION_LOGS": "יומני הזמנה", "DETAIL_SECTION_PAYLOAD": "Payload גולמי של Ticket Tailor", "DETAIL_ACTION_CREATE_PR": "צור בקשת תשלום Nicky", "DETAIL_ACTION_CONFIRM_TT": "אשר תשלום Ticket Tailor", "DETAIL_MAPPING_TT_ORDER": "הזמנת Ticket Tailor", "DETAIL_MAPPING_NICKY_PR": "בקשת תשלום Nicky", "DETAIL_MAPPING_NICKY_BILL": "מזהה קצר של חשבונית Nicky", "DETAIL_MAPPING_NICKY_RECEIVER": "מקבל Nicky", "DETAIL_MAPPING_NICKY_URL": "כתובת תשלום Nicky", "DETAIL_MAPPING_NICKY_STATUS": "סטטוס Nicky", "DETAIL_MAPPING_TT_CONFIRMED": "תשלום Ticket Tailor אושר ב", "DETAIL_MAPPING_TT_VOIDED": "כרטיסים שהונפקו בוטלו ב", "DETAIL_MAPPING_VOID_REASON": "סיבת ביטול הכרטיס", "STATE_CONFIRMED": "תשלום אושר", "STATE_VOIDED": "כרטיסים בוטלו", "STATE_PENDING": "הזמנה ממתינה"},
        "WEBHOOKS": {"TABLE_RECEIVED": "התקבל", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "מקור", "TABLE_TYPE": "סוג", "TABLE_STATUS": "סטטוס", "NO_WEBHOOKS": "לא התקבלו WebHooks עדיין", "NO_WEBHOOKS_HINT": "WebHooks מ-Ticket Tailor ו-Nicky יופיעו כאן.", "FILTER_RECEIVED_FROM": "התקבל מ", "FILTER_RECEIVED_TO": "התקבל עד", "FILTER_ALL": "כל הסטטוסים", "FILTER_PROCESSED": "עובד", "FILTER_FAILED": "נכשל", "FILTER_IGNORED": "הותעלם", "FILTER_RECEIVED": "התקבל"},
        "LOGS": {"TABLE_CREATED": "נוצר", "TABLE_EVENT": "אירוע", "TABLE_MESSAGE": "הודעה", "NO_LOGS": "אין יומנים להזמנה זו."},
        "LANG": {"LABEL": "שפה"},
    },
    "it": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "Tenant", "ORDERS": "Ordini", "LOG_OUT": "Esci"},
        "COMMON": {"ACTIVE": "Attivo", "INACTIVE": "Inattivo", "CONFIGURED": "Configurato", "MISSING": "Mancante", "SAVE_CHANGES": "Salva modifiche", "CREATE": "Crea", "EDIT": "Modifica", "APPLY": "Applica", "CLEAR": "Cancella", "VALIDATE": "Valida", "SHOW": "Mostra", "HIDE": "Nascondi", "COPY": "Copia", "COPIED": "Copiato.", "PREVIOUS": "Precedente", "NEXT": "Successivo", "OPEN": "Apri", "SEARCH": "Cerca", "ALL_TENANTS": "Tutti i Tenant", "ALL_STATUSES": "Tutti gli stati", "ALL_STATES": "Tutti gli stati", "ALL_CONFIGURATIONS": "Tutte le configurazioni", "SHOWING": "Visualizzazione", "OF": "di", "PAGE": "Pagina", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "Admin", "SUPPORT": "Supporto", "USER": "Utente"},
        "DASHBOARD": {"TITLE": "Dashboard di integrazione", "SUBTITLE": "Visualizzazione operativa per i pagamenti offline di Ticket Tailor e le richieste di pagamento Nicky.", "CUSTOMER_CONNECTIONS": "Connessioni clienti", "RECENT_WEBHOOKS": "WebHook recenti", "RECENT_ORDERS": "Ordini recenti", "METRIC_TENANTS": "Tenant", "METRIC_TOTAL_ORDERS": "Ordini totali", "METRIC_TOTAL_WEBHOOKS": "WebHook totali", "METRIC_ACTIVE": "{{count}} attivi", "METRIC_ALL_TIME": "di sempre"},
        "TENANTS": {"TITLE": "Connessioni clienti", "SUBTITLE": "Gestisci la connessione Ticket Tailor, l'account di pagamento Nicky e la configurazione del webhook di ogni cliente.", "BUTTON_NEW": "Nuovo Tenant", "NO_TENANTS": "Nessun Tenant configurato", "NO_TENANTS_HINT": "Crea un Tenant per collegare un account Ticket Tailor con Nicky.", "TABLE_NICKY_EMAIL": "Email Nicky", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "Asset", "TABLE_CREATED": "Creato", "TABLE_UPDATED": "Aggiornato", "FILTER_ACTIVE": "Attivo", "FILTER_CONFIG": "Configurazione", "FILTER_CONFIGURED": "Configurato", "FILTER_MISSING": "Configurazione mancante", "FILTER_PLACEHOLDER": "Tenant o nome", "FILTER_ACTIVE_OPTION": "Attivo", "FILTER_INACTIVE_OPTION": "Inattivo", "FORM_TITLE_NEW": "Nuovo Tenant", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "Nome", "FORM_LABEL_UUID": "UUID Tenant", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "Email Nicky", "FORM_LABEL_ASSET": "Asset", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "Incolla la API key Nicky", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "Lascia vuoto per mantenere quella esistente", "FORM_PLACEHOLDER_TT_KEY_NEW": "Incolla la API key di Ticket Tailor", "FORM_PLACEHOLDER_TT_KEY_EDIT": "Lascia vuoto per mantenere quella esistente", "FORM_PLACEHOLDER_ASSET": "Valida prima la API key Nicky", "FORM_BUTTON_CREATE": "Crea Tenant", "FORM_BUTTON_SAVE": "Salva modifiche", "FORM_BUTTON_BACK": "Torna ai Tenant", "FORM_BUTTON_DEACTIVATE": "Disattiva Tenant", "FORM_WEBHOOK_TITLE": "WebHook Ticket Tailor", "FORM_WEBHOOK_HINT": "Copia l'URL di questo microservizio WebHook e configuralo in Ticket Tailor in Impostazioni > API > WebHook.", "NOTICE_SAVED": "Tenant salvato.", "NOTICE_WEBHOOK_FAILED": "Tenant salvato, ma la registrazione del WebHook Nicky è fallita — riprova più tardi.", "VALIDATION_VALIDATING": "Validazione in corso...", "VALIDATION_NICKY_OK": "API key Nicky validata.", "VALIDATION_TT_OK": "API key Ticket Tailor validata.", "VALIDATION_ERROR_NICKY_EMPTY": "Incolla prima una API key Nicky.", "VALIDATION_ERROR_TT_EMPTY": "Incolla prima una API key di Ticket Tailor.", "VALIDATION_FAILED": "Validazione fallita"},
        "ORDERS": {"TITLE": "Ordini", "SUBTITLE": "Ordini Ticket Tailor mappati alle Richieste di Pagamento Nicky.", "NO_ORDERS": "Nessun ordine acquisito", "NO_ORDERS_HINT": "Gli ordini appaiono qui quando Ticket Tailor invia un WebHook per un pagamento offline Nicky.", "TABLE_ORDER": "Ordine", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "Acquirente", "TABLE_AMOUNT": "Importo", "TABLE_NICKY_PR": "PR Nicky", "TABLE_NICKY_STATUS": "Stato Nicky", "TABLE_TT_STATE": "Stato Ticket Tailor", "TABLE_UPDATED": "Aggiornato", "FILTER_UPDATED_FROM": "Aggiornato dal", "FILTER_UPDATED_TO": "Aggiornato al", "FILTER_ALL_STATES": "Tutti gli stati", "FILTER_PENDING": "Ordine in attesa", "FILTER_CONFIRMED": "Pagamento confermato", "FILTER_VOIDED": "Biglietti annullati", "DETAIL_BUTTON_BACK": "Torna agli ordini", "DETAIL_SECTION_MAPPING": "Mappatura ordine", "DETAIL_SECTION_ACTIONS": "Azioni", "DETAIL_SECTION_LOGS": "Log ordine", "DETAIL_SECTION_PAYLOAD": "Payload grezzo Ticket Tailor", "DETAIL_ACTION_CREATE_PR": "Crea Richiesta di Pagamento Nicky", "DETAIL_ACTION_CONFIRM_TT": "Conferma pagamento Ticket Tailor", "DETAIL_MAPPING_TT_ORDER": "Ordine Ticket Tailor", "DETAIL_MAPPING_NICKY_PR": "Richiesta di Pagamento Nicky", "DETAIL_MAPPING_NICKY_BILL": "ID breve fattura Nicky", "DETAIL_MAPPING_NICKY_RECEIVER": "Destinatario Nicky", "DETAIL_MAPPING_NICKY_URL": "URL pagamento Nicky", "DETAIL_MAPPING_NICKY_STATUS": "Stato Nicky", "DETAIL_MAPPING_TT_CONFIRMED": "Pagamento Ticket Tailor confermato il", "DETAIL_MAPPING_TT_VOIDED": "Biglietti emessi annullati il", "DETAIL_MAPPING_VOID_REASON": "Motivo annullamento biglietto", "STATE_CONFIRMED": "Pagamento confermato", "STATE_VOIDED": "Biglietti annullati", "STATE_PENDING": "Ordine in attesa"},
        "WEBHOOKS": {"TABLE_RECEIVED": "Ricevuto", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "Sorgente", "TABLE_TYPE": "Tipo", "TABLE_STATUS": "Stato", "NO_WEBHOOKS": "Nessun WebHook ricevuto", "NO_WEBHOOKS_HINT": "I WebHook di Ticket Tailor e Nicky appariranno qui.", "FILTER_RECEIVED_FROM": "Ricevuto dal", "FILTER_RECEIVED_TO": "Ricevuto al", "FILTER_ALL": "Tutti gli stati", "FILTER_PROCESSED": "Elaborato", "FILTER_FAILED": "Fallito", "FILTER_IGNORED": "Ignorato", "FILTER_RECEIVED": "Ricevuto"},
        "LOGS": {"TABLE_CREATED": "Creato", "TABLE_EVENT": "Evento", "TABLE_MESSAGE": "Messaggio", "NO_LOGS": "Nessun log per questo ordine."},
        "LANG": {"LABEL": "Lingua"},
    },
    "nl": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "Tenants", "ORDERS": "Bestellingen", "LOG_OUT": "Uitloggen"},
        "COMMON": {"ACTIVE": "Actief", "INACTIVE": "Inactief", "CONFIGURED": "Geconfigureerd", "MISSING": "Ontbreekt", "SAVE_CHANGES": "Wijzigingen opslaan", "CREATE": "Aanmaken", "EDIT": "Bewerken", "APPLY": "Toepassen", "CLEAR": "Wissen", "VALIDATE": "Valideren", "SHOW": "Tonen", "HIDE": "Verbergen", "COPY": "Kopiëren", "COPIED": "Gekopieerd.", "PREVIOUS": "Vorige", "NEXT": "Volgende", "OPEN": "Openen", "SEARCH": "Zoeken", "ALL_TENANTS": "Alle Tenants", "ALL_STATUSES": "Alle statussen", "ALL_STATES": "Alle statussen", "ALL_CONFIGURATIONS": "Alle configuraties", "SHOWING": "Weergave", "OF": "van", "PAGE": "Pagina", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "Admin", "SUPPORT": "Ondersteuning", "USER": "Gebruiker"},
        "DASHBOARD": {"TITLE": "Integratiedashboard", "SUBTITLE": "Operationeel overzicht voor Ticket Tailor offline betalingen en Nicky betalingsverzoeken.", "CUSTOMER_CONNECTIONS": "Klantverbindingen", "RECENT_WEBHOOKS": "Recente WebHooks", "RECENT_ORDERS": "Recente bestellingen", "METRIC_TENANTS": "Tenants", "METRIC_TOTAL_ORDERS": "Totaal bestellingen", "METRIC_TOTAL_WEBHOOKS": "Totaal WebHooks", "METRIC_ACTIVE": "{{count}} actief", "METRIC_ALL_TIME": "aller tijden"},
        "TENANTS": {"TITLE": "Klantverbindingen", "SUBTITLE": "Beheer de Ticket Tailor-verbinding, het Nicky-betaalaccount en de webhookconfiguratie van elke klant.", "BUTTON_NEW": "Nieuwe Tenant", "NO_TENANTS": "Nog geen Tenants geconfigureerd", "NO_TENANTS_HINT": "Maak een Tenant aan om een Ticket Tailor-account te koppelen aan Nicky.", "TABLE_NICKY_EMAIL": "Nicky e-mail", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "Asset", "TABLE_CREATED": "Aangemaakt", "TABLE_UPDATED": "Bijgewerkt", "FILTER_ACTIVE": "Actief", "FILTER_CONFIG": "Configuratie", "FILTER_CONFIGURED": "Geconfigureerd", "FILTER_MISSING": "Configuratie ontbreekt", "FILTER_PLACEHOLDER": "Tenant of naam", "FILTER_ACTIVE_OPTION": "Actief", "FILTER_INACTIVE_OPTION": "Inactief", "FORM_TITLE_NEW": "Nieuwe Tenant", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "Naam", "FORM_LABEL_UUID": "Tenant UUID", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "Nicky e-mail", "FORM_LABEL_ASSET": "Asset", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "Plak Nicky API key", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "Leeg laten om bestaande te behouden", "FORM_PLACEHOLDER_TT_KEY_NEW": "Plak Ticket Tailor API key", "FORM_PLACEHOLDER_TT_KEY_EDIT": "Leeg laten om bestaande te behouden", "FORM_PLACEHOLDER_ASSET": "Valideer eerst de Nicky API key", "FORM_BUTTON_CREATE": "Tenant aanmaken", "FORM_BUTTON_SAVE": "Wijzigingen opslaan", "FORM_BUTTON_BACK": "Terug naar Tenants", "FORM_BUTTON_DEACTIVATE": "Tenant deactiveren", "FORM_WEBHOOK_TITLE": "Ticket Tailor WebHook", "FORM_WEBHOOK_HINT": "Kopieer deze microservice WebHook-URL en configureer deze in Ticket Tailor via Instellingen > API > WebHook.", "NOTICE_SAVED": "Tenant opgeslagen.", "NOTICE_WEBHOOK_FAILED": "Tenant opgeslagen, maar registratie van de Nicky WebHook is mislukt — probeer het later opnieuw.", "VALIDATION_VALIDATING": "Valideren...", "VALIDATION_NICKY_OK": "Nicky API key gevalideerd.", "VALIDATION_TT_OK": "Ticket Tailor API key gevalideerd.", "VALIDATION_ERROR_NICKY_EMPTY": "Plak eerst een Nicky API key.", "VALIDATION_ERROR_TT_EMPTY": "Plak eerst een Ticket Tailor API key.", "VALIDATION_FAILED": "Validatie mislukt"},
        "ORDERS": {"TITLE": "Bestellingen", "SUBTITLE": "Ticket Tailor-bestellingen gekoppeld aan Nicky betalingsverzoeken.", "NO_ORDERS": "Nog geen bestellingen vastgelegd", "NO_ORDERS_HINT": "Bestellingen verschijnen hier wanneer Ticket Tailor een WebHook stuurt voor een Nicky offline betaling.", "TABLE_ORDER": "Bestelling", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "Koper", "TABLE_AMOUNT": "Bedrag", "TABLE_NICKY_PR": "Nicky PR", "TABLE_NICKY_STATUS": "Nicky status", "TABLE_TT_STATE": "Ticket Tailor status", "TABLE_UPDATED": "Bijgewerkt", "FILTER_UPDATED_FROM": "Bijgewerkt van", "FILTER_UPDATED_TO": "Bijgewerkt tot", "FILTER_ALL_STATES": "Alle statussen", "FILTER_PENDING": "Bestelling in behandeling", "FILTER_CONFIRMED": "Betaling bevestigd", "FILTER_VOIDED": "Tickets geannuleerd", "DETAIL_BUTTON_BACK": "Terug naar bestellingen", "DETAIL_SECTION_MAPPING": "Bestellingskoppeling", "DETAIL_SECTION_ACTIONS": "Acties", "DETAIL_SECTION_LOGS": "Bestellingslogboek", "DETAIL_SECTION_PAYLOAD": "Ruwe Ticket Tailor Payload", "DETAIL_ACTION_CREATE_PR": "Nicky betalingsverzoek aanmaken", "DETAIL_ACTION_CONFIRM_TT": "Ticket Tailor-betaling bevestigen", "DETAIL_MAPPING_TT_ORDER": "Ticket Tailor-bestelling", "DETAIL_MAPPING_NICKY_PR": "Nicky betalingsverzoek", "DETAIL_MAPPING_NICKY_BILL": "Nicky factuur kort-id", "DETAIL_MAPPING_NICKY_RECEIVER": "Nicky ontvanger", "DETAIL_MAPPING_NICKY_URL": "Nicky betaal-URL", "DETAIL_MAPPING_NICKY_STATUS": "Nicky status", "DETAIL_MAPPING_TT_CONFIRMED": "Ticket Tailor-betaling bevestigd op", "DETAIL_MAPPING_TT_VOIDED": "Uitgegeven tickets geannuleerd op", "DETAIL_MAPPING_VOID_REASON": "Reden annulering ticket", "STATE_CONFIRMED": "Betaling bevestigd", "STATE_VOIDED": "Tickets geannuleerd", "STATE_PENDING": "Bestelling in behandeling"},
        "WEBHOOKS": {"TABLE_RECEIVED": "Ontvangen", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "Bron", "TABLE_TYPE": "Type", "TABLE_STATUS": "Status", "NO_WEBHOOKS": "Nog geen WebHooks ontvangen", "NO_WEBHOOKS_HINT": "WebHooks van Ticket Tailor en Nicky verschijnen hier.", "FILTER_RECEIVED_FROM": "Ontvangen van", "FILTER_RECEIVED_TO": "Ontvangen tot", "FILTER_ALL": "Alle statussen", "FILTER_PROCESSED": "Verwerkt", "FILTER_FAILED": "Mislukt", "FILTER_IGNORED": "Genegeerd", "FILTER_RECEIVED": "Ontvangen"},
        "LOGS": {"TABLE_CREATED": "Aangemaakt", "TABLE_EVENT": "Gebeurtenis", "TABLE_MESSAGE": "Bericht", "NO_LOGS": "Geen logboeken voor deze bestelling."},
        "LANG": {"LABEL": "Taal"},
    },
    "zh-Hans": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "租户", "ORDERS": "订单", "LOG_OUT": "退出登录"},
        "COMMON": {"ACTIVE": "活跃", "INACTIVE": "未激活", "CONFIGURED": "已配置", "MISSING": "缺失", "SAVE_CHANGES": "保存更改", "CREATE": "创建", "EDIT": "编辑", "APPLY": "应用", "CLEAR": "清除", "VALIDATE": "验证", "SHOW": "显示", "HIDE": "隐藏", "COPY": "复制", "COPIED": "已复制。", "PREVIOUS": "上一页", "NEXT": "下一页", "OPEN": "打开", "SEARCH": "搜索", "ALL_TENANTS": "所有租户", "ALL_STATUSES": "所有状态", "ALL_STATES": "所有状态", "ALL_CONFIGURATIONS": "所有配置", "SHOWING": "显示", "OF": "共", "PAGE": "页", "TENANT": "租户", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "管理员", "SUPPORT": "客服", "USER": "用户"},
        "DASHBOARD": {"TITLE": "集成 Dashboard", "SUBTITLE": "Ticket Tailor 线下支付与 Nicky 支付请求的运营视图。", "CUSTOMER_CONNECTIONS": "客户连接", "RECENT_WEBHOOKS": "最近的 WebHook", "RECENT_ORDERS": "最近订单", "METRIC_TENANTS": "租户", "METRIC_TOTAL_ORDERS": "总订单数", "METRIC_TOTAL_WEBHOOKS": "总 WebHook 数", "METRIC_ACTIVE": "{{count}} 个活跃", "METRIC_ALL_TIME": "累计"},
        "TENANTS": {"TITLE": "客户连接", "SUBTITLE": "管理每位客户的 Ticket Tailor 连接、Nicky 支付账户及 WebHook 配置。", "BUTTON_NEW": "新建租户", "NO_TENANTS": "暂无已配置的租户", "NO_TENANTS_HINT": "创建一个租户以将 Ticket Tailor 账户与 Nicky 连接。", "TABLE_NICKY_EMAIL": "Nicky 邮箱", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "资产", "TABLE_CREATED": "创建时间", "TABLE_UPDATED": "更新时间", "FILTER_ACTIVE": "活跃", "FILTER_CONFIG": "配置", "FILTER_CONFIGURED": "已配置", "FILTER_MISSING": "配置缺失", "FILTER_PLACEHOLDER": "租户或名称", "FILTER_ACTIVE_OPTION": "活跃", "FILTER_INACTIVE_OPTION": "未激活", "FORM_TITLE_NEW": "新建租户", "FORM_TITLE_EDIT": "租户", "FORM_SECTION_TENANT": "租户", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "名称", "FORM_LABEL_UUID": "租户 UUID", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "Nicky 邮箱", "FORM_LABEL_ASSET": "资产", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "粘贴 Nicky API key", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "留空以保留现有密钥", "FORM_PLACEHOLDER_TT_KEY_NEW": "粘贴 Ticket Tailor API key", "FORM_PLACEHOLDER_TT_KEY_EDIT": "留空以保留现有密钥", "FORM_PLACEHOLDER_ASSET": "请先验证 Nicky API key", "FORM_BUTTON_CREATE": "创建租户", "FORM_BUTTON_SAVE": "保存更改", "FORM_BUTTON_BACK": "返回租户列表", "FORM_BUTTON_DEACTIVATE": "停用租户", "FORM_WEBHOOK_TITLE": "Ticket Tailor WebHook", "FORM_WEBHOOK_HINT": "复制此微服务 WebHook URL 并在 Ticket Tailor 的设置 > API > WebHook 中进行配置。", "NOTICE_SAVED": "租户已保存。", "NOTICE_WEBHOOK_FAILED": "租户已保存，但 Nicky WebHook 注册失败 — 请稍后重试。", "VALIDATION_VALIDATING": "验证中...", "VALIDATION_NICKY_OK": "Nicky API key 验证成功。", "VALIDATION_TT_OK": "Ticket Tailor API key 验证成功。", "VALIDATION_ERROR_NICKY_EMPTY": "请先粘贴 Nicky API key。", "VALIDATION_ERROR_TT_EMPTY": "请先粘贴 Ticket Tailor API key。", "VALIDATION_FAILED": "验证失败"},
        "ORDERS": {"TITLE": "订单", "SUBTITLE": "Ticket Tailor 订单与 Nicky 支付请求的映射关系。", "NO_ORDERS": "暂无订单记录", "NO_ORDERS_HINT": "当 Ticket Tailor 为 Nicky 线下支付发送 WebHook 时，订单将显示于此。", "TABLE_ORDER": "订单", "TABLE_TENANT": "租户", "TABLE_BUYER": "买家", "TABLE_AMOUNT": "金额", "TABLE_NICKY_PR": "Nicky PR", "TABLE_NICKY_STATUS": "Nicky 状态", "TABLE_TT_STATE": "Ticket Tailor 状态", "TABLE_UPDATED": "更新时间", "FILTER_UPDATED_FROM": "更新时间从", "FILTER_UPDATED_TO": "更新时间至", "FILTER_ALL_STATES": "所有状态", "FILTER_PENDING": "订单待处理", "FILTER_CONFIRMED": "支付已确认", "FILTER_VOIDED": "票据已作废", "DETAIL_BUTTON_BACK": "返回订单列表", "DETAIL_SECTION_MAPPING": "订单映射", "DETAIL_SECTION_ACTIONS": "操作", "DETAIL_SECTION_LOGS": "订单日志", "DETAIL_SECTION_PAYLOAD": "原始 Ticket Tailor Payload", "DETAIL_ACTION_CREATE_PR": "创建 Nicky 支付请求", "DETAIL_ACTION_CONFIRM_TT": "确认 Ticket Tailor 支付", "DETAIL_MAPPING_TT_ORDER": "Ticket Tailor 订单", "DETAIL_MAPPING_NICKY_PR": "Nicky 支付请求", "DETAIL_MAPPING_NICKY_BILL": "Nicky 账单短 ID", "DETAIL_MAPPING_NICKY_RECEIVER": "Nicky 收款方", "DETAIL_MAPPING_NICKY_URL": "Nicky 支付链接", "DETAIL_MAPPING_NICKY_STATUS": "Nicky 状态", "DETAIL_MAPPING_TT_CONFIRMED": "Ticket Tailor 支付确认时间", "DETAIL_MAPPING_TT_VOIDED": "已发票据作废时间", "DETAIL_MAPPING_VOID_REASON": "票据作废原因", "STATE_CONFIRMED": "支付已确认", "STATE_VOIDED": "票据已作废", "STATE_PENDING": "订单待处理"},
        "WEBHOOKS": {"TABLE_RECEIVED": "接收时间", "TABLE_TENANT": "租户", "TABLE_SOURCE": "来源", "TABLE_TYPE": "类型", "TABLE_STATUS": "状态", "NO_WEBHOOKS": "暂无 WebHook 记录", "NO_WEBHOOKS_HINT": "来自 Ticket Tailor 和 Nicky 的 WebHook 将显示于此。", "FILTER_RECEIVED_FROM": "接收时间从", "FILTER_RECEIVED_TO": "接收时间至", "FILTER_ALL": "所有状态", "FILTER_PROCESSED": "已处理", "FILTER_FAILED": "失败", "FILTER_IGNORED": "已忽略", "FILTER_RECEIVED": "已接收"},
        "LOGS": {"TABLE_CREATED": "创建时间", "TABLE_EVENT": "事件", "TABLE_MESSAGE": "消息", "NO_LOGS": "该订单暂无日志。"},
        "LANG": {"LABEL": "语言"},
    },
    "ru": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "Tenant", "ORDERS": "Заказы", "LOG_OUT": "Выйти"},
        "COMMON": {"ACTIVE": "Активный", "INACTIVE": "Неактивный", "CONFIGURED": "Настроен", "MISSING": "Отсутствует", "SAVE_CHANGES": "Сохранить изменения", "CREATE": "Создать", "EDIT": "Редактировать", "APPLY": "Применить", "CLEAR": "Очистить", "VALIDATE": "Проверить", "SHOW": "Показать", "HIDE": "Скрыть", "COPY": "Копировать", "COPIED": "Скопировано.", "PREVIOUS": "Назад", "NEXT": "Далее", "OPEN": "Открыть", "SEARCH": "Поиск", "ALL_TENANTS": "Все Tenant", "ALL_STATUSES": "Все статусы", "ALL_STATES": "Все состояния", "ALL_CONFIGURATIONS": "Все конфигурации", "SHOWING": "Показано", "OF": "из", "PAGE": "Страница", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "Администратор", "SUPPORT": "Поддержка", "USER": "Пользователь"},
        "DASHBOARD": {"TITLE": "Dashboard интеграции", "SUBTITLE": "Операционный обзор офлайн-платежей Ticket Tailor и запросов на оплату Nicky.", "CUSTOMER_CONNECTIONS": "Подключения клиентов", "RECENT_WEBHOOKS": "Последние WebHook", "RECENT_ORDERS": "Последние заказы", "METRIC_TENANTS": "Tenant", "METRIC_TOTAL_ORDERS": "Всего заказов", "METRIC_TOTAL_WEBHOOKS": "Всего WebHook", "METRIC_ACTIVE": "{{count}} активных", "METRIC_ALL_TIME": "за всё время"},
        "TENANTS": {"TITLE": "Подключения клиентов", "SUBTITLE": "Управляйте подключением Ticket Tailor, платёжным аккаунтом Nicky и настройкой WebHook для каждого клиента.", "BUTTON_NEW": "Новый Tenant", "NO_TENANTS": "Tenant ещё не настроены", "NO_TENANTS_HINT": "Создайте Tenant, чтобы связать аккаунт Ticket Tailor с Nicky.", "TABLE_NICKY_EMAIL": "Email Nicky", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "Актив", "TABLE_CREATED": "Создан", "TABLE_UPDATED": "Обновлён", "FILTER_ACTIVE": "Активный", "FILTER_CONFIG": "Конфигурация", "FILTER_CONFIGURED": "Настроен", "FILTER_MISSING": "Конфигурация отсутствует", "FILTER_PLACEHOLDER": "Tenant или имя", "FILTER_ACTIVE_OPTION": "Активный", "FILTER_INACTIVE_OPTION": "Неактивный", "FORM_TITLE_NEW": "Новый Tenant", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "Имя", "FORM_LABEL_UUID": "UUID Tenant", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "Email Nicky", "FORM_LABEL_ASSET": "Актив", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "Вставьте API key Nicky", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "Оставьте пустым, чтобы сохранить текущий", "FORM_PLACEHOLDER_TT_KEY_NEW": "Вставьте API key Ticket Tailor", "FORM_PLACEHOLDER_TT_KEY_EDIT": "Оставьте пустым, чтобы сохранить текущий", "FORM_PLACEHOLDER_ASSET": "Сначала проверьте API key Nicky", "FORM_BUTTON_CREATE": "Создать Tenant", "FORM_BUTTON_SAVE": "Сохранить изменения", "FORM_BUTTON_BACK": "Назад к Tenant", "FORM_BUTTON_DEACTIVATE": "Деактивировать Tenant", "FORM_WEBHOOK_TITLE": "WebHook Ticket Tailor", "FORM_WEBHOOK_HINT": "Скопируйте URL WebHook этого микросервиса и настройте его в Ticket Tailor в разделе Настройки > API > WebHook.", "NOTICE_SAVED": "Tenant сохранён.", "NOTICE_WEBHOOK_FAILED": "Tenant сохранён, но регистрация WebHook Nicky не удалась — повторите попытку позже.", "VALIDATION_VALIDATING": "Проверка...", "VALIDATION_NICKY_OK": "API key Nicky проверен.", "VALIDATION_TT_OK": "API key Ticket Tailor проверен.", "VALIDATION_ERROR_NICKY_EMPTY": "Сначала вставьте API key Nicky.", "VALIDATION_ERROR_TT_EMPTY": "Сначала вставьте API key Ticket Tailor.", "VALIDATION_FAILED": "Проверка не пройдена"},
        "ORDERS": {"TITLE": "Заказы", "SUBTITLE": "Заказы Ticket Tailor, сопоставленные с запросами на оплату Nicky.", "NO_ORDERS": "Заказы ещё не зафиксированы", "NO_ORDERS_HINT": "Заказы появятся здесь, когда Ticket Tailor отправит WebHook для офлайн-платежа Nicky.", "TABLE_ORDER": "Заказ", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "Покупатель", "TABLE_AMOUNT": "Сумма", "TABLE_NICKY_PR": "PR Nicky", "TABLE_NICKY_STATUS": "Статус Nicky", "TABLE_TT_STATE": "Состояние Ticket Tailor", "TABLE_UPDATED": "Обновлён", "FILTER_UPDATED_FROM": "Обновлён с", "FILTER_UPDATED_TO": "Обновлён по", "FILTER_ALL_STATES": "Все состояния", "FILTER_PENDING": "Заказ в ожидании", "FILTER_CONFIRMED": "Оплата подтверждена", "FILTER_VOIDED": "Билеты аннулированы", "DETAIL_BUTTON_BACK": "Назад к заказам", "DETAIL_SECTION_MAPPING": "Сопоставление заказа", "DETAIL_SECTION_ACTIONS": "Действия", "DETAIL_SECTION_LOGS": "Журнал заказа", "DETAIL_SECTION_PAYLOAD": "Исходный Payload Ticket Tailor", "DETAIL_ACTION_CREATE_PR": "Создать запрос на оплату Nicky", "DETAIL_ACTION_CONFIRM_TT": "Подтвердить оплату Ticket Tailor", "DETAIL_MAPPING_TT_ORDER": "Заказ Ticket Tailor", "DETAIL_MAPPING_NICKY_PR": "Запрос на оплату Nicky", "DETAIL_MAPPING_NICKY_BILL": "Короткий ID счёта Nicky", "DETAIL_MAPPING_NICKY_RECEIVER": "Получатель Nicky", "DETAIL_MAPPING_NICKY_URL": "URL оплаты Nicky", "DETAIL_MAPPING_NICKY_STATUS": "Статус Nicky", "DETAIL_MAPPING_TT_CONFIRMED": "Оплата Ticket Tailor подтверждена", "DETAIL_MAPPING_TT_VOIDED": "Выпущенные билеты аннулированы", "DETAIL_MAPPING_VOID_REASON": "Причина аннулирования билета", "STATE_CONFIRMED": "Оплата подтверждена", "STATE_VOIDED": "Билеты аннулированы", "STATE_PENDING": "Заказ в ожидании"},
        "WEBHOOKS": {"TABLE_RECEIVED": "Получен", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "Источник", "TABLE_TYPE": "Тип", "TABLE_STATUS": "Статус", "NO_WEBHOOKS": "WebHook ещё не получены", "NO_WEBHOOKS_HINT": "WebHook от Ticket Tailor и Nicky появятся здесь.", "FILTER_RECEIVED_FROM": "Получен с", "FILTER_RECEIVED_TO": "Получен по", "FILTER_ALL": "Все статусы", "FILTER_PROCESSED": "Обработан", "FILTER_FAILED": "Ошибка", "FILTER_IGNORED": "Проигнорирован", "FILTER_RECEIVED": "Получен"},
        "LOGS": {"TABLE_CREATED": "Создан", "TABLE_EVENT": "Событие", "TABLE_MESSAGE": "Сообщение", "NO_LOGS": "Нет журналов для этого заказа."},
        "LANG": {"LABEL": "Язык"},
    },
    "el": {
        "NAV": {"DASHBOARD": "Dashboard", "TENANTS": "Tenants", "ORDERS": "Παραγγελίες", "LOG_OUT": "Αποσύνδεση"},
        "COMMON": {"ACTIVE": "Ενεργό", "INACTIVE": "Ανενεργό", "CONFIGURED": "Ρυθμισμένο", "MISSING": "Λείπει", "SAVE_CHANGES": "Αποθήκευση αλλαγών", "CREATE": "Δημιουργία", "EDIT": "Επεξεργασία", "APPLY": "Εφαρμογή", "CLEAR": "Εκκαθάριση", "VALIDATE": "Επαλήθευση", "SHOW": "Εμφάνιση", "HIDE": "Απόκρυψη", "COPY": "Αντιγραφή", "COPIED": "Αντιγράφηκε.", "PREVIOUS": "Προηγούμενο", "NEXT": "Επόμενο", "OPEN": "Άνοιγμα", "SEARCH": "Αναζήτηση", "ALL_TENANTS": "Όλοι οι Tenants", "ALL_STATUSES": "Όλες οι καταστάσεις", "ALL_STATES": "Όλες οι καταστάσεις", "ALL_CONFIGURATIONS": "Όλες οι ρυθμίσεις", "SHOWING": "Εμφάνιση", "OF": "από", "PAGE": "Σελίδα", "TENANT": "Tenant", "PAYLOAD": "Payload"},
        "PROFILE": {"ADMIN": "Διαχειριστής", "SUPPORT": "Υποστήριξη", "USER": "Χρήστης"},
        "DASHBOARD": {"TITLE": "Dashboard ενοποίησης", "SUBTITLE": "Λειτουργική προβολή για offline πληρωμές Ticket Tailor και αιτήματα πληρωμής Nicky.", "CUSTOMER_CONNECTIONS": "Συνδέσεις πελατών", "RECENT_WEBHOOKS": "Πρόσφατα WebHook", "RECENT_ORDERS": "Πρόσφατες παραγγελίες", "METRIC_TENANTS": "Tenants", "METRIC_TOTAL_ORDERS": "Σύνολο παραγγελιών", "METRIC_TOTAL_WEBHOOKS": "Σύνολο WebHook", "METRIC_ACTIVE": "{{count}} ενεργά", "METRIC_ALL_TIME": "όλων των εποχών"},
        "TENANTS": {"TITLE": "Συνδέσεις πελατών", "SUBTITLE": "Διαχειριστείτε τη σύνδεση Ticket Tailor, τον λογαριασμό πληρωμής Nicky και τη ρύθμιση WebHook κάθε πελάτη.", "BUTTON_NEW": "Νέος Tenant", "NO_TENANTS": "Δεν έχουν ρυθμιστεί Tenants ακόμα", "NO_TENANTS_HINT": "Δημιουργήστε έναν Tenant για να συνδέσετε έναν λογαριασμό Ticket Tailor με το Nicky.", "TABLE_NICKY_EMAIL": "Email Nicky", "TABLE_TICKET_TAILOR": "Ticket Tailor", "TABLE_NICKY": "Nicky", "TABLE_ASSET": "Περιουσιακό στοιχείο", "TABLE_CREATED": "Δημιουργήθηκε", "TABLE_UPDATED": "Ενημερώθηκε", "FILTER_ACTIVE": "Ενεργό", "FILTER_CONFIG": "Ρύθμιση", "FILTER_CONFIGURED": "Ρυθμισμένο", "FILTER_MISSING": "Ελλιπής ρύθμιση", "FILTER_PLACEHOLDER": "Tenant ή όνομα", "FILTER_ACTIVE_OPTION": "Ενεργό", "FILTER_INACTIVE_OPTION": "Ανενεργό", "FORM_TITLE_NEW": "Νέος Tenant", "FORM_TITLE_EDIT": "Tenant", "FORM_SECTION_TENANT": "Tenant", "FORM_SECTION_NICKY": "Nicky", "FORM_SECTION_TICKET_TAILOR": "Ticket Tailor", "FORM_LABEL_NAME": "Όνομα", "FORM_LABEL_UUID": "UUID Tenant", "FORM_LABEL_API_KEY": "API key", "FORM_LABEL_NICKY_EMAIL": "Email Nicky", "FORM_LABEL_ASSET": "Περιουσιακό στοιχείο", "FORM_PLACEHOLDER_NICKY_KEY_NEW": "Επικολλήστε το API key Nicky", "FORM_PLACEHOLDER_NICKY_KEY_EDIT": "Αφήστε κενό για διατήρηση του υπάρχοντος", "FORM_PLACEHOLDER_TT_KEY_NEW": "Επικολλήστε το API key Ticket Tailor", "FORM_PLACEHOLDER_TT_KEY_EDIT": "Αφήστε κενό για διατήρηση του υπάρχοντος", "FORM_PLACEHOLDER_ASSET": "Επαληθεύστε πρώτα το API key Nicky", "FORM_BUTTON_CREATE": "Δημιουργία Tenant", "FORM_BUTTON_SAVE": "Αποθήκευση αλλαγών", "FORM_BUTTON_BACK": "Επιστροφή στους Tenants", "FORM_BUTTON_DEACTIVATE": "Απενεργοποίηση Tenant", "FORM_WEBHOOK_TITLE": "WebHook Ticket Tailor", "FORM_WEBHOOK_HINT": "Αντιγράψτε αυτό το URL WebHook microservice και ρυθμίστε το στο Ticket Tailor μέσω Ρυθμίσεις > API > WebHook.", "NOTICE_SAVED": "Ο Tenant αποθηκεύτηκε.", "NOTICE_WEBHOOK_FAILED": "Ο Tenant αποθηκεύτηκε, αλλά η καταχώριση WebHook Nicky απέτυχε — δοκιμάστε ξανά αργότερα.", "VALIDATION_VALIDATING": "Επαλήθευση...", "VALIDATION_NICKY_OK": "Το API key Nicky επαληθεύτηκε.", "VALIDATION_TT_OK": "Το API key Ticket Tailor επαληθεύτηκε.", "VALIDATION_ERROR_NICKY_EMPTY": "Επικολλήστε πρώτα ένα API key Nicky.", "VALIDATION_ERROR_TT_EMPTY": "Επικολλήστε πρώτα ένα API key Ticket Tailor.", "VALIDATION_FAILED": "Η επαλήθευση απέτυχε"},
        "ORDERS": {"TITLE": "Παραγγελίες", "SUBTITLE": "Παραγγελίες Ticket Tailor αντιστοιχισμένες σε αιτήματα πληρωμής Nicky.", "NO_ORDERS": "Δεν έχουν καταγραφεί παραγγελίες ακόμα", "NO_ORDERS_HINT": "Οι παραγγελίες εμφανίζονται εδώ όταν το Ticket Tailor στέλνει WebHook για offline πληρωμή Nicky.", "TABLE_ORDER": "Παραγγελία", "TABLE_TENANT": "Tenant", "TABLE_BUYER": "Αγοραστής", "TABLE_AMOUNT": "Ποσό", "TABLE_NICKY_PR": "PR Nicky", "TABLE_NICKY_STATUS": "Κατάσταση Nicky", "TABLE_TT_STATE": "Κατάσταση Ticket Tailor", "TABLE_UPDATED": "Ενημερώθηκε", "FILTER_UPDATED_FROM": "Ενημερώθηκε από", "FILTER_UPDATED_TO": "Ενημερώθηκε έως", "FILTER_ALL_STATES": "Όλες οι καταστάσεις", "FILTER_PENDING": "Παραγγελία σε αναμονή", "FILTER_CONFIRMED": "Πληρωμή επιβεβαιώθηκε", "FILTER_VOIDED": "Εισιτήρια ακυρώθηκαν", "DETAIL_BUTTON_BACK": "Επιστροφή στις παραγγελίες", "DETAIL_SECTION_MAPPING": "Αντιστοίχιση παραγγελίας", "DETAIL_SECTION_ACTIONS": "Ενέργειες", "DETAIL_SECTION_LOGS": "Αρχεία καταγραφής παραγγελίας", "DETAIL_SECTION_PAYLOAD": "Ακατέργαστο Payload Ticket Tailor", "DETAIL_ACTION_CREATE_PR": "Δημιουργία αιτήματος πληρωμής Nicky", "DETAIL_ACTION_CONFIRM_TT": "Επιβεβαίωση πληρωμής Ticket Tailor", "DETAIL_MAPPING_TT_ORDER": "Παραγγελία Ticket Tailor", "DETAIL_MAPPING_NICKY_PR": "Αίτημα πληρωμής Nicky", "DETAIL_MAPPING_NICKY_BILL": "Σύντομο ID λογαριασμού Nicky", "DETAIL_MAPPING_NICKY_RECEIVER": "Παραλήπτης Nicky", "DETAIL_MAPPING_NICKY_URL": "URL πληρωμής Nicky", "DETAIL_MAPPING_NICKY_STATUS": "Κατάσταση Nicky", "DETAIL_MAPPING_TT_CONFIRMED": "Πληρωμή Ticket Tailor επιβεβαιώθηκε στις", "DETAIL_MAPPING_TT_VOIDED": "Εκδοθέντα εισιτήρια ακυρώθηκαν στις", "DETAIL_MAPPING_VOID_REASON": "Αιτία ακύρωσης εισιτηρίου", "STATE_CONFIRMED": "Πληρωμή επιβεβαιώθηκε", "STATE_VOIDED": "Εισιτήρια ακυρώθηκαν", "STATE_PENDING": "Παραγγελία σε αναμονή"},
        "WEBHOOKS": {"TABLE_RECEIVED": "Ελήφθη", "TABLE_TENANT": "Tenant", "TABLE_SOURCE": "Πηγή", "TABLE_TYPE": "Τύπος", "TABLE_STATUS": "Κατάσταση", "NO_WEBHOOKS": "Δεν έχουν ληφθεί WebHook ακόμα", "NO_WEBHOOKS_HINT": "Τα WebHook από Ticket Tailor και Nicky θα εμφανιστούν εδώ.", "FILTER_RECEIVED_FROM": "Ελήφθη από", "FILTER_RECEIVED_TO": "Ελήφθη έως", "FILTER_ALL": "Όλες οι καταστάσεις", "FILTER_PROCESSED": "Επεξεργάστηκε", "FILTER_FAILED": "Απέτυχε", "FILTER_IGNORED": "Αγνοήθηκε", "FILTER_RECEIVED": "Ελήφθη"},
        "LOGS": {"TABLE_CREATED": "Δημιουργήθηκε", "TABLE_EVENT": "Συμβάν", "TABLE_MESSAGE": "Μήνυμα", "NO_LOGS": "Δεν υπάρχουν αρχεία καταγραφής για αυτή την παραγγελία."},
        "LANG": {"LABEL": "Γλώσσα"},
    },
}

for lc, content in translations.items():
    path = base / f"{lc}.json"
    path.write_text(json.dumps(content, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {lc}.json ({path.stat().st_size} bytes)")

print("done")
